### ISSUE TITLE
make assets-build failed

### ISSUE THREAD

**Issue by jugrajsingh** [imWildCat/scylla#105]
**Describe the bug**
make assets-build failed w=while making from source

**To Reproduce**
follow the install from source steps and at make assets-build it failed

**Expected behavior**
successful build
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser chrome

**Comment by imWildCat** [comment]
Could you please provide the full logs?

**Comment by slavaGanzin** [comment]
hi @imWildCat had same issue:

```
make assets-build
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/home/vganzin/work/wagthedog/scylla'
make assets-clean
make[2]: Entering directory '/home/vganzin/work/wagthedog/scylla'
rm -rf scylla/assets
rm -rf build/lib/scylla/assets
rm -rf dist/scylla/scylla/assets
make[2]: Leaving directory '/home/vganzin/work/wagthedog/scylla'
NODE_ENV=production parcel build --public-url='/assets' -d scylla/assets frontend/src/index.html
error: unknown option '-d'
```

You should use node_modules/.bin/parcel in make file!
