### ISSUE TITLE
sqlite3.h错误

### ISSUE THREAD

**Issue by wjy19990622** [imWildCat/scylla#108]
playhouse\_sqlite_ext.c(531): fatal error C1083: 无法打开包括文件: “sqlite3.h”: No such file or
directory

**Comment by wjy19990622** [comment]
playhouse\_sqlite_ext.c(531): fatal error C1083: 无法打开包括文件: “sqlite3.h”: No such file or
directory

**Comment by imWildCat** [comment]
Please find the answer at:

https://www.bing.com/search?q=%E2%80%9Csqlite3.h%E2%80%9D%3A+No+such+file+or+directory&qs=n&form=QBRE&sp=-1&pq=%E2%80%9Csqlite3.h%E2%80%9D%3A+no+such+file+or+directory&sc=0-38&sk=&cvid=E4314B0D6DF14DF38D5AFA687BE379A1

Because it is unrelated to this project.
