### ISSUE TITLE
Cannot get this url: https://raw.githubusercontent.com/a2u/free-proxy-list/master/free-proxy-list.txt

### ISSUE THREAD

**Issue by cnjiangjun** [imWildCat/scylla#131]
Please provide the following information if applicable:

WARNING: [Worker] Cannot get this url: https://raw.githubusercontent.com/a2u/free-proxy-list/master/free-proxy-list.txt

**Comment by undernewmanagement** [comment]
Just poked this Sept 2022, seems to work again, FWIW
