### ISSUE TITLE
NameError: name 'CIMultiDict' is not defined

### ISSUE THREAD

**Issue by yewang173** [imWildCat/scylla#157]
NameError: name 'CIMultiDict' is not defined

**Comment by Divine420** [comment]
I stumbled upon the project and got excited, only to get thrown this same error. Looks like imWildCat abandoned this, As there isn't any activity. This is an awesome project and I hope someone picks it up, Until then I'll keep troubleshooting.

**Comment by imWildCat** [comment]
Are you using Docker or the source code?

**Comment by Divine420** [comment]
> Are you using Docker or the source code?

I'm using the latest version of Docker

**Comment by imWildCat** [comment]
Could you try the latest version again?

**Comment by Divine420** [comment]
Working flawlessly for me now, Thanks so much.
