### ISSUE TITLE
Feature request: Forward proxy

### ISSUE THREAD

**Issue by imWildCat** [imWildCat/scylla#17]
**Is your feature request related to a problem? Please describe.**
A forward proxy would make this project much easier to use because it can hide the complexity behind the detail of this proxy pool.
This feature is proposed by @binux.

**Describe the solution you'd like**
Implement a very rough http proxy using Sanic at the very beginning. This proxy will assign proxy ips randomly for the clients.

**Describe alternatives you've considered**
None, at present.

**Additional context**
None.

**Comment by faceair** [comment]
Hi, 我用 Golang 实现了[大半个 forward proxy](https://github.com/faceair/betproxy)，不知道是否可以跟 scylla 结合一下。

1. Golang 性能比 Python 好，调用方怼过来表现可能会更好一点
2. 基于 MITM 支持 HTTPS Proxy，可以拿到到 HTTPS 请求详情

如果能跟 scylla 结合我期望有两个接口供 betproxy 调用：
1. 传递域名给 scylla 获取有效的代理 ip
2. 上报可能失效的代理 ip 和访问失败的域名给 scylla 二次验证或者直接失效掉

不知道你是怎么考虑这块的，betproxy 这边可以为 scylla 调整相关的实现。

**Comment by imWildCat** [comment]
@faceair 

Thanks for your contribution! You proposal looks reasonable.

Regarding [betproxy](https://github.com/faceair/betproxy), the code should have be improved from the aspects including:
- Unit testing
- Documentation (especially English documentation)
- Other *Community Profile*: https://github.com/faceair/betproxy/community
- License

After that, we could start to discuss the integration between this project and Scylla.

In terms of your wishes (or plans):
1. We could use `Docker` implementing a sample `docker-compose.yml` to achieve this goal.
2. As for invalid proxy reporting, authentication of this kind of APIs in Scylla should be implemented first from my point of views.

**Comment by faceair** [comment]
😁OK, I'll finish my project first.
