### ISSUE TITLE
请问这个搜索出来的proxy该如何使用？

### ISSUE THREAD

**Issue by alexya** [imWildCat/scylla#20]
Please provide the following information if applicable:

- Operating system and its version: 
Windows 10 Pro/Mac OSX 10.11.3 (15D21)

- Version number of Scylla:
不清楚，使用的https://scylla-demo.wildcat.io/#/
这个网址搜索

- Version number of your Chromium (if related):
Version 68.0.3439.0 (Official Build) canary (64-bit)

我问的这个问题，好像不是scylla的程序问题，而是搜索结果的问题。
我用的chrome插件 SwitchyOmega，使用的是搜索出来的第一个proxy地址，但是不能用。
Https也修改成SOCKS5，还是不能使用。
![image](https://user-images.githubusercontent.com/2831220/40593617-4218db3a-625c-11e8-90b6-9673bca530b3.png)

![image](https://user-images.githubusercontent.com/2831220/40593652-732d615a-625c-11e8-9c8e-30515120e976.png)

**Comment by imWildCat** [comment]
This technology is not supposed for this kind of purpose, instead, for crawling.

**Comment by lyn716** [comment]
GFW对http代理会有侦测，ss项目就是为了避免这个的，做了更多的识别度混淆。这个项目采集的代理是给搭在海外的爬虫机器使用的，不要搞错了。
