### ISSUE TITLE
can not start scylla on python3 virtualenv

### ISSUE THREAD

**Issue by yangsui9999** [imWildCat/scylla#22]
**Describe the bug**
After installed scylla using pip cannot start scylla

**To Reproduce**
Here's my steps
1. Working with python3 on virtual env.
```
(autocoin) ➜  ~ python
Python 3.6.5 (default, Apr 25 2018, 14:23:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
2. Install scylla
```
pip install scylla
```
3. Start scylla in itermal2
```
scylla
```
4. Got error
error logs:
```
2018-05-28 - 23:30:50 DEBUG: create new connection
2018-05-28 - 23:30:50 INFO: Scheduler starts...
2018-05-28 - 23:30:50 DEBUG: feed 9 providers...
2018-05-28 - 23:30:50 INFO: Start python scheduler
2018-05-28 - 23:30:50 INFO: worker_process started
2018-05-28 - 23:30:50 INFO: validator_thread started
2018-05-28 - 23:30:50 INFO: Start the web server
[2018-05-28 23:30:50 +0800] [27105] [INFO] Goin' Fast @ http://0.0.0.0:8899
2018-05-28 - 23:30:50 DEBUG: fetch_ips...
2018-05-28 - 23:30:50 DEBUG: Get a provider from the provider queue: A2uProvider
[2018-05-28 23:30:50 +0800] [27105] [INFO] Starting worker [27105]
objc[27108]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[27108]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

And I cannot open `http://0.0.0.0:8899/`

**Screenshots**
![image](https://user-images.githubusercontent.com/25709047/40621518-9ecadb12-62cf-11e8-990f-387117afaf06.png)

**Desktop :**
 - OS: macOS 10.13.4

**Comment by imWildCat** [comment]
Thanks for your issue!

I've installed Python 3.6.5 on my Mac and reproduced your problem successfully.

Try add this environment variable before start `scylla`:

```bash
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

If you solve this problem by doing as described above, please let me know.
I'll fix this issue in the source code.

Reference: https://github.com/ansible/ansible/issues/32499#issuecomment-341578864

**Comment by yangsui9999** [comment]
@imWildCat after add `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` to my environment variable, can start scylla right.

**Comment by imWildCat** [comment]
@yangsui9999 Glad to see this. Thank you!
