### ISSUE TITLE
pip3 installation and start failed

### ISSUE THREAD

**Issue by biezhi** [imWildCat/scylla#25]
OS: Mac OS X 10.13.4 x86_64
Scylla Version: latest

I didn't use Chromium. I installed it through pip3 [here](https://scylla.wildcat.io/zh/latest/#pip), there is no error in the installation.

![image](https://user-images.githubusercontent.com/3849072/40696947-ca7caae8-63fa-11e8-98ac-507db1f0ec85.png)

In fact, I should install `sanic` and `sanic_cors` in advance. 

![image](https://user-images.githubusercontent.com/3849072/40697077-393c4e2a-63fb-11e8-8615-c54c770e7066.png)

So this should be recorded in the `README`, and other people may also encounter such problems.

Thank you for writing the software, it's cool 🍻

**Comment by biezhi** [comment]
![image](https://user-images.githubusercontent.com/3849072/40697663-f5149588-63fd-11e8-8340-819830bdbf0a.png)

emmm, what is this?

**Comment by imWildCat** [comment]
Thanks for your issue!

> In fact, I should install sanic and sanic_cors in advance.

These dependencies have been included into the `setup.py`. This should be the problem of your system.

> emmm, what is this?

Duplicate: https://github.com/imWildCat/scylla/issues/22
