### ISSUE TITLE
docker run not work

### ISSUE THREAD

**Issue by XUJiahua** [imWildCat/scylla#28]
**Describe the bug**
docker run not work

```
(base) ➜  ~ docker ps -all
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                     PORTS               NAMES
e50c1035ba1a        wildcat/scylla:latest   "/bin/sh -c 'python …"   16 minutes ago      Exited (1) 2 minutes ago                       scylla
```

**To Reproduce**
1. `docker run -d -p 8899:8899 -p 8081:8081 -v /var/www/scylla:/var/www/scylla --name scylla wildcat/scylla:latest`
2. `docker ps -all`

**Expected behavior**

should work...

**Screenshots**

n/a

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Comment by imWildCat** [comment]
As I mentioned on V2EX, the bug is fixed: https://hub.docker.com/r/wildcat/scylla/builds/bfux3x4pp4m8pg3ehhssckc/
