### ISSUE TITLE
api/v1/stats http 500

### ISSUE THREAD

**Issue by zouhua** [imWildCat/scylla#29]
- docker 跑了1个小时了，1个代理都没
- api/v1/stats http 500
-  scylla                  1.1.2

**scylla       1.0 没问题**

**Comment by zqjilove** [comment]
我也碰到了同样的的问题？ LZ解决了？

**Comment by imWildCat** [comment]
@zqjilove 有可能是这个问题：https://github.com/imWildCat/scylla/issues/30
尝试升级：`1.1.3`
