### ISSUE TITLE
MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))

### ISSUE THREAD

**Issue by pcwang0205** [imWildCat/scylla#41]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/10112141/42485674-45628868-842b-11e8-8cb5-39e519fada8a.png">

**Comment by imWildCat** [comment]
Please provide the following information if applicable:

- Operating system and its version: 
- Version number of Scylla:
- Version number of your Chromium (if related):
