### ISSUE TITLE
Scrapoxy Integration

### ISSUE THREAD

**Issue by fabienvauchelles** [imWildCat/scylla#45]
Hello,

It could be a good idea to integrate [Scrapoxy.io](http://scrapoxy.io) into scylla.

You can add in a minute many hundreds private proxies (open source). Could be interesting.

Best regards,
Fabien

**Comment by imWildCat** [comment]
Hello, @fabienvauchelles , thanks for your suggestion!

Scrapoxy is really a good tool but I am afraid the users of Scrapoxy will be redundant to share their proxies.
