### ISSUE TITLE
Error when proxy via proxifier or proxychains

### ISSUE THREAD

**Issue by Lz1y** [imWildCat/scylla#50]
**Describe the bug**
Error when proxy via proxifier or proxychains.

**To Reproduce**
1. vim /etc/proxychains.conf
2. add proxy "http 127.0.0.1 8081"
3. execute shell "proxychains curl ip.sb"
4. we get "curl: (6) Could not resolve host: ip.sb",and console print "WARNING:tornado.access:405 CONNECT 8.8.8.8:53 (127.0.0.1) 0.52ms"

proxifier will return:
```
[38:18] Error : the proxy server cannot establish connection with www.baidu.com:80
	The error may indicate that the proxy server doesn't support SSL connections.
	It means that the proxy can be used for web browsing but it cannot work with Proxifier.
	The proxy server reply header is:
		HTTP/1.1 405 Method Not Allowed
		Server: TornadoServer/5.0.2
		Content-Type: text/html; charset=UTF-8
		Date: Sun, 23 Dec 2018 11:38:18 GMT
		Content-Length: 87
```

**Expected behavior**
it's should work normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/23468993/50383244-94331380-06ea-11e9-9e28-b43923f2f430.png)

![image](https://user-images.githubusercontent.com/23468993/50383248-9bf2b800-06ea-11e9-8d15-f3048c8ac839.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version lastest

**Comment by imWildCat** [comment]
Thanks for your issue!

Please note that this project is not for your purpose.
For more details, please read: https://github.com/imWildCat/scylla/issues/20#issuecomment-392424089
