### ISSUE TITLE
Not feeding providers after the very first run

### ISSUE THREAD

**Issue by mtndewxu** [imWildCat/scylla#52]
- Operating system and its version: 
Ubuntu 16.04
- Version number of Scylla:
docker image: scylla:latest
- Version number of your Chromium (if related):

So when i start the service via docker run, it does bootstrap a2u and coolproxy but no more. From the log i can see it's trying to feed providers every 10 min but it doesn't seem be running fine.

Screenshot of log:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/22148229/50503803-80016480-0aa4-11e9-8b48-f5f97be08eaa.png">

Any help would be appreciated. Let me know if more information is needed.

Thanks.

**Comment by imWildCat** [comment]
Hello! Where is you machine located?

**Comment by mtndewxu** [comment]
Thanks for quick response. My machine is located in China.

**Comment by imWildCat** [comment]
Hope this will be helpful: https://github.com/imWildCat/scylla/issues/20#issuecomment-392424089

**Comment by imWildCat** [comment]
Yes, you are right.

Please feel free to reopen this issue if needed.

**Comment by mtndewxu** [comment]
Hi there,

So i moved it to a US server but still having same issue. Any idea how to get over it?

<img width="805" alt="image" src="https://user-images.githubusercontent.com/22148229/50592091-97d64f80-0ecd-11e9-96a2-a36833726698.png">

**Comment by imWildCat** [comment]
Could you please try using docker?

**Comment by mtndewxu** [comment]
I'm using docker already. Should I try build from source? 

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/22148229/50593496-8132f700-0ed3-11e9-855e-1c064351fc4c.png">

**Comment by mtndewxu** [comment]
Is it some provider stuck and blocking everything? Maybe i can try disable one or two providers?

**Comment by mtndewxu** [comment]
commented out CoolProxyProvider and it's working now. thanks.
