### ISSUE TITLE
运行几天，但是代理只有70+?

### ISSUE THREAD

**Issue by wenthywang** [imWildCat/scylla#55]
我在70+过滤后，剩下20了，请问代理是从哪里获取的呢？

**Comment by ericxsun** [comment]
see [provider](https://github.com/imWildCat/scylla/tree/master/scylla/providers)

**Comment by yaro97** [comment]
是的, 可用的IP 太少.  用docker运行的 -> 还没有搞定如何添加采集源

**Comment by kushao1267** [comment]
加自定义provider就行了，添加IP采集的入口

**Comment by imWildCat** [comment]
Closed due to unstructured content.
