### ISSUE TITLE
为撒 在代理的时候会报400？

### ISSUE THREAD

**Issue by wenthywang** [imWildCat/scylla#56]
<p>Some aspect of the requested URL is incorrect.</p>

<p>Some possible problems are:</p>
<ul>
<li><p>Missing or incorrect access protocol (should be <q>http://</q> or similar)</p></li>
<li><p>Missing hostname</p></li>
<li><p>Illegal double-escape in the URL-Path</p></li>
<li><p>Illegal character in hostname; underscores are not allowed.</p></li>
</ul>

**Comment by imWildCat** [comment]
Closed due to unstructured content.
